### ISSUE TITLE
Total OCS Crash

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/ocs#205]
Something happened to our system around 2021-06-19T00:24:49+0000 that caused almost our whole setup to go down. 

Things I know:
- We're running OCS 0.8.0
- I don't think the computer restarted, all our containers were still running
- The crossbar docker was still running, but doesn't appear like it was working (either that or the aggregator + influx db publisher quit talking to it). 
- We were running a simple script that was changing the bath temp while calling SMuRF data taking (script ran no problem one I restarted everything). 
- I had to restart the crossbar docker and the aggregator (+our LS readout) on Echo base to get readout working. The pysmurf controller, monitor, and recorder also died. (Bluefors ones did not). 
- We lost a screen session on Echo-base (the one running that simple script)

Logs snippet from one of our Lakeshores. 
```2021-06-19T00:24:49+0000 session left: CloseDetails(reason=<wamp.close.transport_lost>, message='WAMP transport was lost without closing the session 2762108826696918 before')
2021-06-19T00:24:57+0000 OCSAgent.onUserError(): "While firing onLeave"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/autobahn/twisted/websocket.py", line 330, in _onClose
    self.onClose(wasClean, code, reason)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/wamp/websocket.py", line 78, in onClose
    self._session.onClose(wasClean)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/wamp/protocol.py", line 1255, in onClose
    d = txaio.as_future(self.onLeave, details)
  File "/usr/local/lib/python3.6/dist-packages/txaio/tx.py", line 366, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/app/ocs/ocs/ocs_agent.py", line 204, in onLeave
    self.heartbeat_call.stop()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/task.py", line 202, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
builtins.AssertionError: Tried to stop a LoopingCall that was not running.
2021-06-19T00:25:09+0000 transport disconnected
2021-06-19T00:25:14+0000 realm rejoined
2021-06-19T00:25:32+0000 Scheduling retry 1 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x7fb042dd1438> in 2.4585617613263535 seconds.
2021-06-19T00:27:04+0000 Scheduling retry 2 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x7fb042dd1438> in 3.157369761502194 seconds.
2021-06-19T00:31:20+0000 Scheduling retry 3 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x7fb042dd1438> in 3.9984064034947813 seconds.
2021-06-19T00:34:44+0000 Could not publish to Feed. TransportLost. crossbar server likely unreachable.
2021-06-19T00:36:17+0000 Scheduling retry 4 to connect <twisted.internet.endpoints.TCP4ClientEndpoint object at 0x7fb042dd1438> in 6.055778700128627 seconds.
2021-06-19T00:36:32+0000 Could not publish to Feed. TransportLost. crossbar server likely unreachable.
2021-06-19T00:36:34+0000 Could not publish to Feed. TransportLost. crossbar server likely unreachable.
2021-06-19T00:36:36+0000 Could not publish to Feed. TransportLost. crossbar server likely unreachable.
2021-06-19T00:36:37+0000 transport connected
2021-06-19T00:36:37+0000 session joined:
SessionDetails(realm="test_realm",
               session=5489842531142098,
               authid="VGNP-4KSN-NXQX-KQHC-4NCT-3EG4",
               authrole="iocs_agent",
               authmethod="anonymous",
               authprovider="static",
               authextra={'x_cb_node': '24eb78efa597-1', 'x_cb_worker': 'worker001', 'x_cb_peer': 'tcp4:10.0.1.25:33374', 'x_cb_pid': 16},
               serializer="cbor.batched",
               transport="websocket",
               resumed=None,
               resumable=None,
               resume_token=None)
```
Here's the most recent images in our setup:
```
REPOSITORY                                        TAG                      IMAGE ID       CREATED         SIZE
simonsobs/ocs-lakeshore240-agent                  latest                   8bf899901a61   4 weeks ago     2.27GB
simonsobs/ocs-lakeshore372-agent                  latest                   b937d369ba03   4 weeks ago     2.27GB
simonsobs/ocs-crossbar                            latest                   7bd68ff585aa   5 weeks ago     583MB
simonsobs/ocs-influxdb-publisher-agent            v0.7.1-35-gff0c239-dev   80a7df79dee2   3 months ago    2.17GB
simonsobs/ocs-aggregator-agent                    v0.7.1-35-gff0c239-dev   fbc1a7ef003c   3 months ago    2.17GB
simonsobs/ocs-registry-agent                      v0.7.1-35-gff0c239-dev   5a02d37f190e   3 months ago    2.17GB
simonsobs/ocs-web                                 v0.7.1-35-gff0c239-dev   050272786871   3 months ago    2.18GB
simonsobs/ocs-labjack-agent                       v0.1.0-39-g9e4cebf-dev   35e67fe45e68   3 months ago    2.36GB
simonsobs/ocs-labjack-agent                       latest                   1cecbc3a55db   7 months ago    1.82GB
simonsobs/ocs-lakeshore240-agent                  <none>                   7f8403fb3610   7 months ago    1.78GB
simonsobs/ocs-lakeshore372-agent                  <none>                   cdfbf1b020df   7 months ago    1.78GB
grafana/grafana                                   7.3.1                    900b03b57e41   7 months ago    186MB
simonsobs/ocs-influxdb-publisher-agent            latest                   9d112ce9d6d7   7 months ago    1.69GB
simonsobs/ocs-aggregator-agent                    latest                   677c06074515   7 months ago    1.69GB
simonsobs/ocs-registry-agent                      latest                   a41190123b89   7 months ago    1.69GB
simonsobs/ocs-web                                 latest                   20f5774026e6   7 months ago    1.7GB
simonsobs/ocs-crossbar                            <none>                   5737e60421a5   7 months ago    583MB
mariadb                                           10.3                     5a5644205c65   8 months ago    388MB
mariadb                                           <none>                   d8d45007e59a   8 months ago    387MB
mariadb                                           <none>                   eb0d526e9865   10 months ago   388MB
simonsobs/ocs-influxdb-publisher-agent            <none>                   03eacfb54e84   10 months ago   1.78GB
```

**Comment by BrianJKoopman** [comment]
Has this been seen again in the past ~month? If it does happen again, it would be helpful to know which agents are/were running (i.e. output from `docker ps` and `docker container ls -a`).
