### ISSUE TITLE
JSON error passing numpy arrays to ocs client arg

### ISSUE THREAD

**Issue by csierra2** [simonsobs/ocs#313]
This is happening when I pass a numpy array as a kwarg to pysmurf-controller's `take_iv`, e.g.

```
pysmurf_uv31 = matched_client.OCSClient('pysmurf-controller-s4', args=[])
bgs = np.arange(12)
pysmurf_uv31.take_iv.start(kwargs =  {'bias_groups': bgs, 'overbias_wait': 1, 'bias_high': 20})
print( pysmurf_uv31.take_iv.wait() )
```

leads to this error:
```
Traceback (most recent call last):
  File "test_pysmurf_iv.py", line 24, in <module>
    pysmurf_uv31.take_iv.start(kwargs = iv_args)
  File "/home/mcmlab/.local/lib/python3.8/site-packages/ocs/ocs_client.py", line 23, in start
    return OCSReply(*client.request('start', name, params=kwargs))
  File "/home/mcmlab/.local/lib/python3.8/site-packages/ocs/client_http.py", line 99, in request
    return self.call(self.agent_addr + '.ops', action, op_name, params, **kw)
  File "/home/mcmlab/.local/lib/python3.8/site-packages/ocs/client_http.py", line 26, in call
    params = json.dumps({'procedure': procedure,
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
```
The script works if I pass it a list instead.

**Comment by jlashner** [comment]
woah I didn't know you could transfer issues between repos
