### ISSUE TITLE
Aggregator - Sometimes prov is None when removing provider

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/ocs#61]
Sometimes when the aggregator goes to remove a provider it finds `prov` to be `None`. This example occurred when a restarted a Lakeshore 240 Agent. But it doesn't happen every time I restart an agent, which makes me think some sort of race condition is occurring.

```
2019-07-01T21:52:08+0000 Added provider observatory.LSA22Z2.feeds.temperatures (agent sess: 1562017928.4343128) with id 2
2019-07-01T21:52:08+0000 Feed observatory.LSA22Z2.feeds.temperatures is already subscribed to
2019-07-01T21:52:09+0000 Removing provider observatory.LSA22Z2.feeds.temperatures with agent id 1562017600.4147737
2019-07-01T21:53:13+0000 OCSAgent.onUserError(): "While firing <bound method DataAggregator._new_agent_handler of <__main__.DataAggregator object at 0x7f93c3ece2b0>> subscribed under 7891720364125154."
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/autobahn/twisted/websocket.py", line 322, in _onMessage
    self.onMessage(payload, isBinary)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/usr/local/lib/python3.6/dist-packages/autobahn/wamp/protocol.py", line 726, in onMessage
    future = txaio.as_future(handler.fn, *invoke_args, **invoke_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/txaio/tx.py", line 429, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "aggregator_agent.py", line 209, in _new_agent_handler
    if action == 'removed' and prov.agent_id == agent_id:
builtins.AttributeError: 'NoneType' object has no attribute 'agent_id'

2019-07-01T21:53:13+0000 Added provider observatory.LSA22Z2.feeds.temperatures (agent sess: 1562017993.426738) with id 3
```

The relevant lines in the aggregator for context:
```
209             if action == 'removed' and prov.agent_id == agent_id:
210                 self.log.info("Scheduled remove for provider {}"
211                               .format(feed['address']))
212                 prov.remove = True
```

**Comment by jlashner** [comment]
Probably fixed through PR #62
