### ISSUE TITLE
Aggregator API docs failing after Agg 2.0 update

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/ocs#88]
The Aggregator API documentation is failing to build after the Aggregator 2.0 update:
```
WARNING: autodoc: failed to import class 'aggregator_agent.DataAggregator' from module 'agents.aggregator'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/koopman/git/ocs/agents/aggregator/aggregator_agent.py", line 202, in <module>
    class G3FileRotator(core.G3Module):
NameError: name 'core' is not defined
```
This doesn't cause the whole build to fail so it wasn't obvious. The API section on the Aggregator page is now blank though.

**Comment by mhasself** [comment]
Resolved in #90
