### ISSUE TITLE
Socket timeouts when running MatchedClient script on remote computer

### ISSUE THREAD

**Issue by jlashner** [simonsobs/ocs#94]
Currently we're trying to run a MatchedClient script on the UCSD smurf-server, where the crossbar docker is being run on adaq1. I'm seeing inconsistent behavior with my test client script (and max was having this problem with the pysmurf client script) where sometimes the http command doesn't go through, and the script just fails. 

The test script is really simple: 
```
from ocs.matched_client import MatchedClient

pysmurf = MatchedClient('pysmurf-controller', args=[])

script_path = '/config/pysmurf_scripts/test.py'

args = ['--config-file', '/config/pysmurf_config/experiment_ucsd_k2so_cc02-06_lbOnlyBay0.cfg']


print("Running {}...".format(script_path))
pysmurf.run.start(script="/config/pysmurf_scripts/test.py", args=args)
pysmurf.run.wait()

print("Script has finished")
```
Sometimes this works, and it gets to the "Script has finished" part and returns, but sometimes it stalls forever after printing "Running /config/pysmurf_scripts/test.py". Looking at the agent logs, it seems like half of the time the `start` command never makes it to the agent, and half of the time the agent runs the script, but the `wait` command never receives an http response.

I think we need to figure out a robust way to make sure http messages have been received. I haven't tested the behavior with wampy clients, so maybe that's the way to go for remote scripts.

Here's a traceback for when it wasn't even able to create the client object:
```
cryo@smurf-srv14:~/ocs-site-configs/ucsd/smurf-srv14/client_scripts$ python3 pysmurf_control.py
Running /config/pysmurf_scripts/test.py...
^CTraceback (most recent call last):
  File "pysmurf_control.py", line 12, in <module>
    pysmurf.run.wait()
  File "/home/cryo/ocs/ocs/matched_client.py", line 15, in wait
    return client.request('wait', name)
  File "/home/cryo/ocs/ocs/client_http.py", line 77, in request
    return self.call(self.agent_addr + '.ops', action, op_name, params, **kw)
  File "/home/cryo/ocs/ocs/client_http.py", line 26, in call
    r = requests.post(self.call_url, data=params)
  File "/home/cryo/.local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/cryo/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/cryo/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cryo/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/cryo/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/cryo/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/cryo/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/cryo/.local/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/cryo/.local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/cryo/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

**Comment by BrianJKoopman** [comment]
Seems to no longer be a problem.
